"""Add PackType and UserPack models

Revision ID: 2dd4632441ba
Revises: 7d876f8bf483
Create Date: 2025-04-07 20:25:33.438686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dd4632441ba'
down_revision = '7d876f8bf483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_types',
    sa.Column('pack_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recipe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pack_type_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pack_types', schema=None) as batch_op:
        batch_op.create_index('idx_pack_types_name', ['name'], unique=False)

    op.create_table('user_packs',
    sa.Column('user_pack_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack_type_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pack_type_id'], ['pack_types.pack_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_pack_id')
    )
    with op.batch_alter_table('user_packs', schema=None) as batch_op:
        batch_op.create_index('idx_user_packs_pack_type_id', ['pack_type_id'], unique=False)
        batch_op.create_index('idx_user_packs_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_packs_user_opened', ['user_id', 'opened_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_packs', schema=None) as batch_op:
        batch_op.drop_index('idx_user_packs_user_opened')
        batch_op.drop_index('idx_user_packs_user_id')
        batch_op.drop_index('idx_user_packs_pack_type_id')

    op.drop_table('user_packs')
    with op.batch_alter_table('pack_types', schema=None) as batch_op:
        batch_op.drop_index('idx_pack_types_name')

    op.drop_table('pack_types')
    # ### end Alembic commands ###
