"""Add ondelete cascade to FKs in Artwork, Collection, UserFollow

Revision ID: 4486eed7f744
Revises: 2dd4632441ba
Create Date: 2025-04-09 12:05:46.066200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4486eed7f744'
down_revision = '2dd4632441ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_constraint('artworks_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['artist_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('collections_patron_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('collections_artwork_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artworks', ['artwork_id'], ['artwork_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['patron_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_constraint('user_follows_patron_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_follows_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['artist_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['patron_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_follows_artist_id_fkey', 'users', ['artist_id'], ['user_id'])
        batch_op.create_foreign_key('user_follows_patron_id_fkey', 'users', ['patron_id'], ['user_id'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('collections_artwork_id_fkey', 'artworks', ['artwork_id'], ['artwork_id'])
        batch_op.create_foreign_key('collections_patron_id_fkey', 'users', ['patron_id'], ['user_id'])

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('artworks_artist_id_fkey', 'users', ['artist_id'], ['user_id'])

    # ### end Alembic commands ###
