"""add artist_name column to artworks

Revision ID: 6ee0423900e0
Revises: 27491eb3190a
Create Date: 2025-04-10 17:03:59.942645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee0423900e0'
down_revision = '27491eb3190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
