"""Add rarity column to artworks

Revision ID: 7d876f8bf483
Revises: bb5bb13149c8
Create Date: 2025-04-07 19:43:56.750355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d876f8bf483'
down_revision = 'bb5bb13149c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('rarity')

    # ### end Alembic commands ###
