"""add series column to artworks table

Revision ID: 85a3ef946c2a
Revises: 6ee0423900e0
Create Date: 2025-04-10 17:22:41.876798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a3ef946c2a'
down_revision = '6ee0423900e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('series')

    # ### end Alembic commands ###
