"""ensure_tradestatus_enum_values

Revision ID: 8d50a410ce72
Revises: add_metadata_to_user_packs
Create Date: 2025-04-17 12:37:57.733219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d50a410ce72'
down_revision = 'add_metadata_to_user_packs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_packs', schema=None) as batch_op:
        batch_op.alter_column('pack_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_packs', schema=None) as batch_op:
        batch_op.alter_column('pack_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
