"""Initial database setup

Revision ID: bb5bb13149c8
Revises: 
Create Date: 2025-04-07 18:29:23.841481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5bb13149c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='patron', nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("role IN ('artist', 'patron')", name='role_check'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=False)

    op.create_table('artworks',
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('artwork_id')
    )
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.create_index('idx_artworks_artist_id', ['artist_id'], unique=False)
        batch_op.create_index('idx_artworks_created_at', ['created_at'], unique=False)

    op.create_table('user_follows',
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patron_id', 'artist_id')
    )
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.create_index('idx_userfollows_artist_id', ['artist_id'], unique=False)
        batch_op.create_index('idx_userfollows_patron_id', ['patron_id'], unique=False)

    op.create_table('collections',
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patron_id', 'artwork_id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('idx_collections_acquired_at', ['acquired_at'], unique=False)
        batch_op.create_index('idx_collections_artwork_id', ['artwork_id'], unique=False)
        batch_op.create_index('idx_collections_patron_id', ['patron_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index('idx_collections_patron_id')
        batch_op.drop_index('idx_collections_artwork_id')
        batch_op.drop_index('idx_collections_acquired_at')

    op.drop_table('collections')
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index('idx_userfollows_patron_id')
        batch_op.drop_index('idx_userfollows_artist_id')

    op.drop_table('user_follows')
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_index('idx_artworks_created_at')
        batch_op.drop_index('idx_artworks_artist_id')

    op.drop_table('artworks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    # ### end Alembic commands ###
